"""The window's Write with AI flow: parts, preview, consent, generation, cancel and quit."""

import asyncio
from datetime import UTC, datetime
from zoneinfo import ZoneInfo

import pytest
from pytestqt.qtbot import QtBot

from mailbrief.domain.drafting import DraftContextPart, DraftingOutcome, DraftingStatus
from mailbrief.domain.drafts import DraftKind
from mailbrief.domain.preferences import OwnerPreferences
from mailbrief.errors import ConfigurationError
from mailbrief.ports.errors import AuthenticationRequiredError, ProviderError
from mailbrief.services.drafting import DraftingContextError
from mailbrief.ui.main_window import MainWindow
from tests.ui.test_workflow import FakeBackend


@pytest.fixture
def backend() -> FakeBackend:
    result = FakeBackend()
    result.owner_preferences = OwnerPreferences(revision=1, time_zone="UTC")
    return result


@pytest.fixture
def window(qtbot: QtBot, backend: FakeBackend) -> MainWindow:
    result = MainWindow(backend)
    result.zone = ZoneInfo("UTC")
    result.now = lambda: datetime(2026, 9, 28, 15, tzinfo=UTC)
    qtbot.addWidget(result)
    return result


async def settle(window: MainWindow) -> None:
    await window.draft_writes.drain()


async def open_note(window: MainWindow, body: str = "My notes") -> None:
    await window.initialize()
    window.drafts_panel.new_menu.actions()[1].trigger()
    assert window.task is not None
    await window.task
    window.draft_editor.body.setPlainText(body)


async def open_ai(window: MainWindow) -> None:
    window.draft_editor.ai_button.click()
    await settle(window)


async def preview(window: MainWindow) -> None:
    await open_ai(window)
    window.draft_editor.ai_panel.continue_button.click()
    await settle(window)


def ai_calls(backend: FakeBackend, name: str) -> list[tuple[object, ...]]:
    return [call for call in backend.ai_calls if call[0] == name]


async def test_the_button_needs_a_groq_key(window: MainWindow, backend: FakeBackend) -> None:
    backend.ai_ready = False
    await open_note(window)
    assert not window.draft_editor.ai_button.isEnabled()

    backend.ai_ready = True
    await window._refresh_ai_status()
    assert window.draft_editor.ai_button.isEnabled()


async def test_the_panel_offers_the_available_parts(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_parts = frozenset({DraftContextPart.ACTION, DraftContextPart.CURRENT_TEXT})
    await open_note(window)

    await open_ai(window)

    panel = window.draft_editor.ai_panel
    assert not panel.isHidden()
    assert panel.email_box.isHidden()
    assert not panel.action_box.isHidden() and not panel.text_box.isHidden()
    window.draft_editor.ai_button.click()
    assert panel.isHidden()


async def test_first_use_previews_asks_for_consent_then_writes_a_new_version(
    window: MainWindow, backend: FakeBackend
) -> None:
    await open_note(window)
    editor = window.draft_editor
    await open_ai(window)
    editor.ai_panel.instructions.setPlainText("Make it a list.")

    editor.ai_panel.continue_button.click()
    assert not editor._fields.isEnabled()  # The text is frozen until the end.
    await settle(window)

    (call,) = ai_calls(backend, "prepare_drafting")
    assert call[2].instructions == "Make it a list."  # type: ignore[attr-defined]
    assert backend.draft_calls[-1][0] == "autosave_draft"  # Saved before the preview.
    preview_text = editor.ai_panel.preview_text.toPlainText()
    assert preview_text.startswith("MailBrief will send these parts to Groq (fake-model)")
    assert "- Your current text: title and body: 12 characters" in preview_text
    assert "Enable Zero Data Retention first." in preview_text
    assert not editor.ai_panel.send_button.isEnabled()
    editor.ai_panel.agree_box.setChecked(True)
    editor.ai_panel.send_button.click()
    assert editor.status.text() == "Writing with Groq…"
    await settle(window)

    assert editor.body.toPlainText() == "Generated text"
    assert editor.status.text() == "New version v3 from Groq; your previous text is version v2."
    assert editor.missing_line.text() == "Missing context to check: the delivery date"
    assert editor._fields.isEnabled() and not editor.ai_active()
    assert backend.ai_consent
    editor.versions_button.click()
    await settle(window)
    assert "generated by fake-model (warm, short)" in editor.versions_list.item(0).text()


async def test_later_generations_send_without_the_consent_box(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    await open_note(window)
    editor = window.draft_editor

    await preview(window)
    assert editor.ai_panel.agree_box.isHidden()
    editor.ai_panel.send_button.click()
    await settle(window)
    assert not editor.ai_panel.isHidden()  # Still open, ready to write again.
    editor.ai_panel.continue_button.click()
    await settle(window)
    editor.ai_panel.send_button.click()
    await settle(window)

    assert len(ai_calls(backend, "generate_draft")) == 2
    assert editor.draft is not None
    versions = backend.versions[editor.draft.public_id]
    assert len([v for v in versions if v.origin == "generated"]) == 2


async def test_a_declined_or_failed_generation_leaves_the_text(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    await open_note(window)
    editor = window.draft_editor
    backend.ai_outcome = DraftingOutcome(status=DraftingStatus.FAILED, error_code="AI_TIMEOUT")

    await preview(window)
    editor.ai_panel.send_button.click()
    await settle(window)

    assert editor.body.toPlainText() == "My notes"
    assert editor.status.text() == "Groq did not respond in time; retry later."
    assert editor._fields.isEnabled()

    backend.ai_outcome = DraftingOutcome(status=DraftingStatus.FAILED, error_code="AI_REFUSED")
    await preview(window)
    editor.ai_panel.send_button.click()
    await settle(window)
    assert editor.body.toPlainText() == "My notes"
    assert editor.status.text() == (
        "Groq declined to write this draft. Change the instructions or context and try again."
    )

    backend.ai_outcome = DraftingOutcome(status=DraftingStatus.DECLINED)
    await preview(window)
    editor.ai_panel.send_button.click()
    await settle(window)
    assert editor.status.text() == "Nothing was sent: AI drafting needs your consent first."


@pytest.mark.parametrize(
    ("failure", "message"),
    [
        (
            DraftingContextError("That email is no longer in local mail."),
            "That email is no longer in local mail.",
        ),
        (
            AuthenticationRequiredError("signed out"),
            "Connect Gmail to download the email, then try again.",
        ),
        (
            ProviderError("offline"),
            "Gmail is offline or unavailable, so the email couldn't be read.",
        ),
        (
            ConfigurationError("Set MAILBRIEF_GROQ_MODEL."),
            "Choose a Groq model that supports Structured Outputs in Settings.",
        ),
        (RuntimeError("private"), "Couldn't write with Groq. Your text is unchanged."),
    ],
)
async def test_a_failed_preview_says_why_and_unlocks(
    window: MainWindow, backend: FakeBackend, failure: Exception, message: str
) -> None:
    await open_note(window)
    await open_ai(window)
    backend.ai_fail = failure

    window.draft_editor.ai_panel.continue_button.click()
    await settle(window)

    assert window.draft_editor.status.text() == message
    assert window.draft_editor._fields.isEnabled()
    assert ai_calls(backend, "generate_draft") == []


async def test_a_failed_parts_check_says_so(window: MainWindow, backend: FakeBackend) -> None:
    await open_note(window)
    backend.ai_fail = ConfigurationError("Set MAILBRIEF_GROQ_MODEL.")

    await open_ai(window)

    assert window.draft_editor.ai_panel.isHidden()
    assert "Groq model" in window.draft_editor.status.text()
    backend.ai_fail = RuntimeError("x")
    await open_ai(window)
    assert window.draft_editor.status.text() == "Couldn't write with Groq. Your text is unchanged."


async def test_cancelling_a_preview_sends_nothing(window: MainWindow, backend: FakeBackend) -> None:
    await open_note(window)
    editor = window.draft_editor
    await preview(window)

    editor.ai_panel.cancel_button.click()
    await settle(window)

    assert editor.status.text() == "Cancelled. Your text is unchanged."
    assert editor._fields.isEnabled()
    assert ai_calls(backend, "generate_draft") == []


async def test_cancelling_a_generation_stops_it_and_writes_nothing(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    backend.ai_gate = asyncio.Event()
    await open_note(window)
    editor = window.draft_editor
    await preview(window)
    editor.ai_panel.send_button.click()
    for _ in range(5):
        await asyncio.sleep(0)
    assert editor.status.text() == "Writing with Groq…"

    editor.ai_panel.cancel_button.click()
    await settle(window)

    assert editor.body.toPlainText() == "My notes"
    assert editor.status.text() == "Cancelled. Your text is unchanged."
    public_id = editor.draft.public_id  # type: ignore[union-attr]
    assert backend.drafts[public_id].body == "My notes"


async def test_a_cancel_that_arrives_after_the_text_was_stored_shows_it(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    backend.ai_gate = asyncio.Event()
    backend.ai_store_before_gate = True
    await open_note(window)
    editor = window.draft_editor
    await preview(window)
    editor.ai_panel.send_button.click()
    for _ in range(5):
        await asyncio.sleep(0)

    editor.ai_panel.cancel_button.click()
    await settle(window)

    assert editor.body.toPlainText() == "Generated text"
    assert editor.status.text().startswith("Groq finished before Cancel took effect")


async def test_quitting_mid_generation_cancels_and_closes_cleanly(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    backend.ai_gate = asyncio.Event()
    await open_note(window)
    editor = window.draft_editor
    await preview(window)
    editor.ai_panel.send_button.click()
    for _ in range(5):
        await asyncio.sleep(0)

    window.close()
    await window.shutdown()

    assert backend.closed
    public_id = editor.draft.public_id  # type: ignore[union-attr]
    assert backend.drafts[public_id].body == "My notes"
    assert window.draft_writes.idle


async def test_revoking_consent_mentions_drafting(window: MainWindow) -> None:
    await window.initialize()
    await window._revoke_consent()
    assert window.status.text().startswith("AI consent revoked for briefs and drafting")
    assert "drafting" in window.settings_dialog.revoke_button.text()


async def test_a_conflict_while_preparing_keeps_the_text(
    window: MainWindow, backend: FakeBackend
) -> None:
    from mailbrief.services.drafts import DraftConflictError

    await open_note(window)
    await open_ai(window)
    backend.ai_fail = DraftConflictError("stale")

    window.draft_editor.ai_panel.continue_button.click()
    await settle(window)

    assert window.draft_editor.in_conflict
    assert window.draft_editor.body.toPlainText() == "My notes"
    assert DraftKind.NOTE  # The draft kind is unchanged.


async def test_ai_steps_without_an_active_generation_do_nothing(
    window: MainWindow, backend: FakeBackend
) -> None:
    await window._offer_drafting()
    await window._prepare_drafting(window.draft_editor.ai_panel.options())  # type: ignore[arg-type]
    await window._generate_draft(True)
    editor = window.draft_editor
    editor.offer_ai(frozenset())
    editor._send_ai(True)
    editor._cancel_ai()

    assert backend.ai_calls == []
    assert editor.ai_panel.isHidden()


async def test_prepare_refuses_while_the_body_is_too_long(window: MainWindow) -> None:
    await open_note(window, body="x" * 20_001)
    await open_ai(window)

    window.draft_editor.ai_panel.continue_button.click()

    assert "Autosave is paused" in window.draft_editor.status.text()
    assert not window.draft_editor.ai_active()


async def test_cancelling_while_preparing_shows_no_preview(
    window: MainWindow, backend: FakeBackend
) -> None:
    await open_note(window)
    await open_ai(window)
    editor = window.draft_editor
    real_prepare = backend.prepare_drafting

    async def prepare_then_cancel(public_id: str, options: object) -> object:
        plan = await real_prepare(public_id, options)  # type: ignore[arg-type]
        editor.ai_panel.cancel_button.click()
        return plan

    backend.prepare_drafting = prepare_then_cancel  # type: ignore[assignment,method-assign]
    editor.ai_panel.continue_button.click()
    await settle(window)

    assert editor.ai_panel.preview.isHidden()
    assert window._drafting_plan is None


@pytest.mark.parametrize(
    ("outcome", "message"),
    [
        (DraftingOutcome(status=DraftingStatus.CANCELLED), "Cancelled. Your text is unchanged."),
        (
            DraftingOutcome(status=DraftingStatus.FAILED, error_code="DRAFT_CHANGED"),
            "The draft changed before Groq's text could be used. Nothing was lost; try again.",
        ),
    ],
)
async def test_other_outcomes_explain_themselves(
    window: MainWindow, backend: FakeBackend, outcome: DraftingOutcome, message: str
) -> None:
    backend.ai_consent = True
    backend.ai_outcome = outcome
    await open_note(window)
    await preview(window)

    window.draft_editor.ai_panel.send_button.click()
    await settle(window)

    assert window.draft_editor.status.text() == message


async def test_an_unexpected_generation_error_leaves_the_text(
    window: MainWindow, backend: FakeBackend
) -> None:
    await open_note(window)
    await preview(window)

    async def broken(*_args: object) -> DraftingOutcome:
        raise RuntimeError("private")

    backend.generate_draft = broken  # type: ignore[assignment,method-assign]
    window.draft_editor.ai_panel.agree_box.setChecked(True)
    window.draft_editor.ai_panel.send_button.click()
    await settle(window)

    assert window.draft_editor.status.text() == "Couldn't write with Groq. Your text is unchanged."
    assert window.draft_editor.body.toPlainText() == "My notes"


async def test_a_failed_check_after_cancel_is_only_logged(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    backend.ai_gate = asyncio.Event()
    await open_note(window)
    editor = window.draft_editor
    await preview(window)
    editor.ai_panel.send_button.click()
    for _ in range(5):
        await asyncio.sleep(0)
    backend.draft_fail = RuntimeError("database locked")

    editor.ai_panel.cancel_button.click()
    await settle(window)

    assert editor.status.text() == "Cancelled. Your text is unchanged."


async def test_a_new_version_refreshes_an_open_versions_list(
    window: MainWindow, backend: FakeBackend
) -> None:
    backend.ai_consent = True
    await open_note(window)
    editor = window.draft_editor
    editor.versions_button.click()
    await settle(window)
    await preview(window)

    editor.ai_panel.send_button.click()
    await settle(window)

    assert editor.versions_list.count() == 3
